config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: "users/sessions" }
  devise_scope :user do
    post '/users', to: 'users/registrations#create'
    get '/users/password', to: 'devise/passwords#new'
    get '/users', to: 'devise/registrations#new'
  end
  root to: 'pages#index'

  resources :categories, except:[:show] do
    resources :tasks, shallow: true
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # relation
  has_many :tasks, dependent: :destroy
  belongs_to :user
  # validation
  validates :title, presence: true, length: { maximum: 50 }

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :title, presence: true
  
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # relation
  has_many :categories
  has_many :tasks
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :find_category, only: %i[edit update show destroy]
  before_action :authenticate_user!
  def index
    @categories = current_user.categories.order(id: :desc)
    @categories = current_user.categories.where('title like ?', "%#{params[:keyword]}%").order(id: :desc) if params[:keyword]
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Create succeed!!'
    else
      render :new
    end
  end

  # def show
  #   @tasks = @category.tasks
  # end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Update succeed!!'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed'
  end

  private

  def find_category
    @category = current_user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only:[:edit, :update, :destroy]
  before_action :find_category, only: [:update, :destroy]

  def index
    @category = current_user.categories.find(params[:category_id])
    @tasks = @category.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @category = current_user.categories.find(params[:category_id])
    @task = @category.tasks.new(task_params)
    if @task.save
      redirect_to category_tasks_path(@category), notice: "Create succeed"
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to category_tasks_path(@category), notice:"Update succeed!!"
    else
      render :edit
    end
  end


  def destroy
    @task.destroy
    redirect_to category_tasks_path(@category), notice:"Task was successfully destroyed"
  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :state, :position)
  end

  def find_category
    @category = current_user.categories.find(@task.category_id)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
    end

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: %i[username])
    end

    def after_sign_up_path_for(_resource)
      categories_path
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

def after_sign_in_path_for(resource)
  categories_path
end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<div class="flex flex-col items-center">
  <div class="mb-3 xl:w-96">
    <% if category.errors.full_messages.any? %>
      <div class="text-red-500">
        <ul>
          <% category.errors.full_messages.each do |error_message| %>
            <li>
              <%= error_message %> <br />
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model:category, class:"flex flex-col items-center"  do |f| %>
      <div class="mb-5">
        <%= f.label :title, "title", class: "form-label inline-block mb-2 text-gray-700" %>
        <%= f.text_field :title, class: "form-control block w-full px-3 py-1.5 text-gray-700 bg-white border border-solid border-gray-300 rounded focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
      </div>
      <div>
        <%= f.submit class:"px-2 py-1 bg-blue-200 rounded-md  hover:bg-blue-600 hover:text-white"   %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-3xl text-center mb-5">Edit Category</h1>
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="flex flex-col items-center">
  <h1 class="text-5xl mb-5">Categories list</h1>
  <form action="./categories" method="get" class="mb-5">
    <input type="text" placeholder="Keywords for title" name="keyword" class="px-5 border border-gray-700 rounded-md pl-9 pr-3 " required="">
    <button type="submit" class="px-2 py-1 rounded-md bg-gray-200 hover:bg-gray-600 hover:text-white">Search</button>
  </form>
</div>
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center">
          <thead class="border-b bg-gray-50">
            <tr>
              <th scope="col" class="text-sm font-medium px-6 py-4">
                Title
              </th>
              <th scope="col" class="text-sm font-medium px-6 py-4">
                Action
              </th>
            </tr>
          </thead class="border-b">
          <tbody>
            <% @categories.each do |category| %>
              <tr class="bg-white border-b">
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap hover:text-red-500" ><%= link_to "#{category.title}",category_tasks_path(category) %></td>
                <td >
                  <%= link_to 'Edit', edit_category_path(category), class:"font-medium text-blue-600 dark:text-blue-500 hover:underline mr-5"%>
                  <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"font-medium text-red-600 dark:text-red-500 hover:underline"%>
                </td>
              </tr class="bg-white border-b">
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="flex justify-center">
  <%= link_to "Create Category", new_category_path, class:"px-3 py-2 bg-blue-200 rounded-md  hover:bg-blue-600 hover:text-white" %>
</div>

app/views/categories/new.html.erb
<h1 class="text-3xl text-center mb-5">Create Category</h1>
<%= render "form", category: @category %>

app/views/layouts/_header.html.erb
<nav class="bg-gray-800 mb-5">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Heroicon name: outline/bars-3

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x-mark

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center mr-5">
          <a href="/">
            <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
            <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </a>
        </div>
        <% if user_signed_in? %>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <a href="/categories" class="text-gray-300 px-3 py-2 hover:bg-gray-700 rounded-md text-sm font-medium" >Categories</a>
              <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Calendar</a>
            </div>
          </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          <!-- Profile dropdown -->
          <div class="relative ml-3">
            <div>
              <button type="button" class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="https://www.w3schools.com/howto/img_avatar.png" alt="">
              </button>
            </div>
          </div>
        </div>
        <div class="text-gray-300 ml-5" >Hi, <%= current_user.username %></div>
        <%= link_to "Sign out", destroy_user_session_path, method: "delete", class:"ml-5 text-gray-300 hover:bg-gray-700 rounded-md px-3 py-2" %>
      <% else %>
        <div class="flex items-center">
          <%= link_to "Sign in", new_user_session_path, class:"ml-3 text-gray-300" %>
          <%= link_to "Registration", new_user_registration_path, class:"ml-8 text-gray-300"%>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if notice  %>
      <p class="notice bg-blue-100 rounded-lg py-5 px-6 mb-4 text-base text-blue-700 mb-3"><%= notice  %></p>
    <% end %>
    <% if alert %>
      <p class="alert bg-red-100 rounded-lg py-5 px-6 mb-4 text-base text-red-700 mb-3"><%= alert if alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<section class="bg-gray-50">
  <div class="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center">
    <div class="mx-auto max-w-xl text-center">
      <h1 class="text-3xl font-extrabold sm:text-5xl">
        To Do List
        <strong class="font-extrabold text-blue-700 sm:block">
          Bring efficiency to you
        </strong>
      </h1>
      <p class="mt-4 sm:text-xl sm:leading-relaxed">
        Press button below, create your account and manage list now!
      </p>
      <div class="mt-8 flex flex-wrap justify-center gap-4">
        <%= link_to "Get Started for Registration", new_user_registration_path, class:"block w-full rounded bg-indigo-600 px-12 py-3 text-sm font-medium text-white shadow hover:bg-indigo-700 focus:outline-none focus:ring active:bg-indigo-500 sm:w-auto"%>
      </div>
    </div>
  </div>
</section>

app/views/tasks/edit.html.erb
<div class="flex flex-col items-center">
  <div class="mb-3 xl:w-96">
    <h1 class="text-3xl mb-5">Edit Task</h1>
    <% if @task.errors.full_messages.any? %>
      <div class="text-red-500">
        <ul>
          <% @task.errors.full_messages.each do |error_message| %>
            <li>
              <%= error_message %> <br />
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @task, url: task_path, method: :patch, class:"flex flex-col items-center" do |f| %>
      <div class="mb-5">
        <%= f.label :title, "title", class: "form-label inline-block mb-2 text-gray-700" %>
        <%= f.text_field :title, class: "form-control block w-full px-3 py-1.5 text-gray-700 bg-white border border-solid border-gray-300 rounded focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
      </div>
      <div class="mb-5">
        <%= f.label :content, "content", class:"form-label inline-block mb-2 text-gray-700" %>
        <%= f.text_field :content, class: "form-control block w-full px-3 py-1.5 text-gray-700 bg-white border border-solid border-gray-300 rounded focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
      </div>
      <div>
        <%= f.submit "Edit", class:"px-2 py-1 bg-green-200 rounded-md  hover:bg-green-600 hover:text-white"   %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="flex flex-col items-center">
  <h2 class="text-5xl mb-10 "><%= @category.title %></h2>
</div>
<div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="p-4">
          <div class="flex items-center">
            <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
            <label for="checkbox-all-search" class="sr-only">checkbox</label>
          </div>
        </th>
        <th scope="col" class="py-3 px-6">
          Task title
        </th>
        <th scope="col" class="py-3 px-6">
          Content
        </th>
        <th scope="col" class="py-3 px-6">
          Action
        </th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
          <td class="p-4 w-4">
            <div class="flex items-center">
              <input id="checkbox-table-search-1" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
              <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
            </div>
          </td>
          <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <%= task.title %>
          </th>
          <td class="py-4 px-6">
            <%= task.content %>
          </td>
          <td class="flex items-center py-4 px-6 space-x-3">
            <%= link_to 'Edit', edit_task_path(task), class:"font-medium text-blue-600 dark:text-blue-500 hover:underline mr-5" %>
            <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' },class:"font-medium text-red-600 dark:text-red-500 hover:underline" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="flex justify-center">
  <%= link_to "Create Task", new_category_task_path(@category), class:"px-3 py-2 bg-green-200 rounded-md  hover:bg-green-600 hover:text-white"%>
</div>

app/views/tasks/new.html.erb
<h1>create task</h1>
<%= form_with model: @task, url: category_tasks_path do |f| %>
  <div>
    <%= f.label :title, "title" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content, "content" %>
    <%= f.text_field :content %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/tasks/show.html.erb
<h1>@task.title</h1>
<p>@task.content</p>